// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Seq                  string   `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Queue                string   `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSeq() string {
	if m != nil {
		return m.Seq
	}
	return ""
}

func (m *Message) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

func (m *Message) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Ack struct {
	Seq                  string   `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetSeq() string {
	if m != nil {
		return m.Seq
	}
	return ""
}

type ConsumerConnect struct {
	Queue                string   `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumerConnect) Reset()         { *m = ConsumerConnect{} }
func (m *ConsumerConnect) String() string { return proto.CompactTextString(m) }
func (*ConsumerConnect) ProtoMessage()    {}
func (*ConsumerConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ConsumerConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerConnect.Unmarshal(m, b)
}
func (m *ConsumerConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerConnect.Marshal(b, m, deterministic)
}
func (m *ConsumerConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerConnect.Merge(m, src)
}
func (m *ConsumerConnect) XXX_Size() int {
	return xxx_messageInfo_ConsumerConnect.Size(m)
}
func (m *ConsumerConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerConnect.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerConnect proto.InternalMessageInfo

func (m *ConsumerConnect) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "grpc.Message")
	proto.RegisterType((*Ack)(nil), "grpc.Ack")
	proto.RegisterType((*ConsumerConnect)(nil), "grpc.ConsumerConnect")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56,
	0x8a, 0xe7, 0x62, 0xf7, 0x85, 0x08, 0x0b, 0x09, 0x70, 0x31, 0x17, 0xa7, 0x16, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x85, 0xa5, 0xa9, 0xa5, 0xa9, 0x12,
	0x4c, 0x60, 0x31, 0x08, 0x47, 0x48, 0x88, 0x8b, 0xa5, 0x24, 0x31, 0xbd, 0x58, 0x82, 0x59, 0x81,
	0x59, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x92, 0xe0, 0x62, 0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c,
	0x91, 0x60, 0x51, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x95, 0xc4, 0xb9, 0x98, 0x1d, 0x93, 0xb3,
	0x31, 0x0d, 0x57, 0x52, 0xe7, 0xe2, 0x77, 0xce, 0xcf, 0x2b, 0x2e, 0xcd, 0x4d, 0x2d, 0x72, 0xce,
	0xcf, 0xcb, 0x4b, 0x4d, 0x2e, 0x41, 0xd8, 0xc7, 0x88, 0x64, 0x9f, 0x51, 0x32, 0x54, 0x54, 0xc8,
	0x98, 0x8b, 0x1d, 0xaa, 0x43, 0x48, 0x54, 0x0f, 0xe4, 0x7a, 0x3d, 0x34, 0x03, 0xa4, 0x78, 0x21,
	0xc2, 0x50, 0x1f, 0x29, 0x31, 0x18, 0x30, 0x0a, 0xa9, 0x72, 0xb1, 0xbb, 0xe6, 0x41, 0xf4, 0xa3,
	0xca, 0x4a, 0x71, 0x42, 0xb8, 0x8e, 0xc9, 0xd9, 0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0x40, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x2e, 0x63, 0xfd, 0x25, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueueClient is the client API for Queue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueueClient interface {
	Consume(ctx context.Context, in *ConsumerConnect, opts ...grpc.CallOption) (Queue_ConsumeClient, error)
	Enqueue(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error)
}

type queueClient struct {
	cc *grpc.ClientConn
}

func NewQueueClient(cc *grpc.ClientConn) QueueClient {
	return &queueClient{cc}
}

func (c *queueClient) Consume(ctx context.Context, in *ConsumerConnect, opts ...grpc.CallOption) (Queue_ConsumeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Queue_serviceDesc.Streams[0], "/grpc.queue/Consume", opts...)
	if err != nil {
		return nil, err
	}
	x := &queueConsumeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Queue_ConsumeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type queueConsumeClient struct {
	grpc.ClientStream
}

func (x *queueConsumeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queueClient) Enqueue(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/grpc.queue/Enqueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServer is the server API for Queue service.
type QueueServer interface {
	Consume(*ConsumerConnect, Queue_ConsumeServer) error
	Enqueue(context.Context, *Message) (*Ack, error)
}

// UnimplementedQueueServer can be embedded to have forward compatible implementations.
type UnimplementedQueueServer struct {
}

func (*UnimplementedQueueServer) Consume(req *ConsumerConnect, srv Queue_ConsumeServer) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (*UnimplementedQueueServer) Enqueue(ctx context.Context, req *Message) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enqueue not implemented")
}

func RegisterQueueServer(s *grpc.Server, srv QueueServer) {
	s.RegisterService(&_Queue_serviceDesc, srv)
}

func _Queue_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumerConnect)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueueServer).Consume(m, &queueConsumeServer{stream})
}

type Queue_ConsumeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type queueConsumeServer struct {
	grpc.ServerStream
}

func (x *queueConsumeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Queue_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.queue/Enqueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Enqueue(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Queue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.queue",
	HandlerType: (*QueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _Queue_Enqueue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _Queue_Consume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}
